[tool.poetry]
name = "my-backtest-lib"
version = "0.1.0"
description = "A backtest engine for financial strategies."
authors = ["Arthur Hottier"]

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"